@uri=http://127.0.0.1:3005/api

###

GET {{uri}}/albums
###

GET {{uri}}/albums/sz

###
# query params
GET {{uri}}/albums?sort=ArtistId

###
# req.params -- returns specific id (259)
GET {{uri}}/albums/1

###
# Inserts row  -- Not wokring
POST {{uri}}/albums
Content-Type: application/json

{
  "Title": "bobbert"

}

###
# Updates row w/ router.put by AlbumId (349)
PUT {{uri}}/albums/353
Content-Type: application/json

{
  "Title": "Bonni"
}

###
# Deletes row specified by :id
DELETE {{uri}}/albums/351