@uri=http://127.0.0.1:3005/api

###
#1 GET all artists
GET {{uri}}/artists

###
#2 query params GET all artists by ArtistId desc
GET {{uri}}/artists?sort=ArtistId

###
#3 req.params -- returns specific artist by id 
GET {{uri}}/artists/sales

###
#4 returns Artists[.id, .name] Albums[.id, Title, ArtistId]
GET {{uri}}/artists/1

###
#
GET {{uri}}/artists/albumss

###
#5 req.params -- returns specified album by :id 
GET {{uri}}/artists/1

###
#6 Inserts row
POST {{uri}}/artists
Content-Type: application/json

{
  "Name": ""
}

###
#7 Updates row w/ router.put by :Id (349)  
PUT {{uri}}/artists/285
Content-Type: application/json

{
  "Name": "jkl"
}

###
#8 Deletes row specified by :id 
DELETE {{uri}}/artists/278