@uri=http://127.0.0.1:3005/api

###
#1 GETS all customers
GET {{uri}}/customers

###
#2 query params - GETS all customrs by Id desc
GET {{uri}}/customers?sort=CustomerId

###
#3 Customers and Invoices 
GET {{uri}}/customers/invoices

###
#4 req.params Speified customer 
GET {{uri}}/customers/56

###
#5 returns specified invoice by :id -- Verify w/ the general
GET {{uri}}/customers/20/invoices

###
#6 Inserts
POST {{uri}}/customers
Content-Type: application/json

{
      "FirstName": "PunChinese",
      "LastName": "Srivava",
      "Address": "3,Raj Bhavan Road",
      "City": "Bangalore",
      "State": "OH",
      "Country": "India",
      "PostalCode": "560001",
      "Phone": "+91 080 22289999",
      "Email": "puja_sa@yahoo.in"
    }

###
#7 updates
PUT {{uri}}/customers/64
Content-Type: application/json

{
  "FirstName": "odee",
  "LastName": "Hadda-litleLam"
}

###
#8 DELETE by :id
DELETE {{uri}}/customers/61