@uri=http://127.0.0.1:3005/api

###
GET {{uri}}/employees

###
# query params
GET {{uri}}/employees?sort=EmployeeId

###
# req.params returns employee with EmployeeId of 7
GET {{uri}}/employees/7

###
# req.params
# staff with managers
GET {{uri}}/employees/staff


###
# req.params staff members with ReportsTo:1
# staff members who ReportsTo: andrew
GET {{uri}}/employees/1/staff

###
# customers whos SupportRepId:3
GET {{uri}}/employees/3/customers



###
# ReportsTo needed to be INT
POST {{uri}}/employees
Content-Type: application/json

{
  "FirstName": "od",
  "LastName": "Mart",
  "Title": "stock-Discos",
  "ReportsTo": 1,
  "BirthDate": "2000-03-11",
  "HireDate": "2018-13-08",
  "Address": "Dr. Falcão Filho, 1555",
  "City": "Paulo",
  "State": "FL",
  "Country": "Brazil",
  "PostalCode": "01007-01011",
  "Phone": "+55 (11) 3033-3789",
  "Fax": "+55 (11) 3033-9873",
  "Email": "do@woodstock.com.br"
}
###
# updates
PUT {{uri}}/employees/7
Content-Type: application/json

{
  "LastName": "Mart",
  "FirstName": "od",
  "Title": "stock-Discos",
  "ReportsTo": "Muad",
  "BirthDate": "2000-03-11",
  "HireDate": "2018-13-08",
  "Address": "Dr. Falcão Filho, 1555",
  "City": "Paulo",
  "State": "FL",
  "Country": "Brazil",
  "PostalCode": "01007-01011",
  "Phone": "+55 (11) 3033-3789",
  "Fax": "+55 (11) 3033-9873",
  "Email": "do@woodstock.com.br"
}

###
DELETE {{uri}}/employees/60