@uri=http://127.0.0.1:3005/api

###
GET {{uri}}/employees

###
# query params
GET {{uri}}/employees?sort=EmployeeId

###
# req.params returns employee with EmployeeId of 7
GET {{uri}}/employees/3/cust

###
# req.params
# staff with managers
GET {{uri}}/employees/staff


###
# req.params staff members with ReportsTo:1
# staff members who ReportsTo: andrew
GET {{uri}}/employees/1/staff

###
# customers whos SupportRepId:3
GET {{uri}}/employees/3/customers



###
# ReportsTo needed to be INT
POST {{uri}}/employees
Content-Type: application/json

{
  "FirstName": "pop",
  "LastName": "Martha",
  "ReportsTo": "1",
  "BirthDate": "2010-13-07",
  "HireDate": "2018-13-08",
  "Address": "Dr. Falcão Filho, 1555",
  "City": "Paulo",
  "State": "FL",
  "Country": "Germany",
  "Phone": "+55 (11) 3033-3789",
  "Email": "do@woodstock.com.br"
}
###
# updates
PUT {{uri}}/employees/14
Content-Type: application/json

  {   
  "LastName": "Martini"
  }

###
DELETE {{uri}}/employees/60