@uri=http://127.0.0.1:3005/api

###
GET {{uri}}/genres

###
# query params
GET {{uri}}/genres?sort=GenreId

###
# req.params -- returns specific id 
GET {{uri}}/genres/20


###
# Inserts row
POST {{uri}}/genres
Content-Type: application/json

{
  "Name": "od-music"
}

###
# Updates row w/ router.put by :Id
PUT {{uri}}/genres/25
Content-Type: application/json

{
  "Name": "Lil-Baby"
}

###
# Deletes row specified by :id 
DELETE {{uri}}/genres/278