@uri=http://127.0.0.1:3005/api

###
# 1
GET {{uri}}/invoices

###
# 2 sorted invoices 
GET {{uri}}/invoices?sort=CustomerId

### 
#3 req.params -- returns invoices with invoice_items
GET {{uri}}/invoices/invoice_items

###
# req.params -- returns specific id 
GET {{uri}}/invoices/256

###
# Inserts row 
POST {{uri}}/invoices
Content-Type: application/json

{
    "CustomerId": 59,
    "InvoiceDate": "2012-2-2 00:00:00",
    "BillingAddress": "12,Commun",
    "BillingCity": "Deli",
    "BillingState": "FL",
    "BillingCountry": "Indiana",
    "BillingPostalCode": "1017",
    "Total": 7.99
  }
###
# Updates row w/ router.put by  primaryKey :Id 
PUT {{uri}}/invoices/413
Content-Type: application/json

{
    "CustomerId": 59,
    "InvoiceDate": "2012-2-2 00:00:00",
    "BillingAddress": "12,Commun",
    "BillingCity": "Delic",
    "BillingState": "FLawda",
    "BillingCountry": "India",
    "BillingPostalCode": "1017",
    "Total": 7.99
  }

###
# Deletes row specified by :id
DELETE {{uri}}/invoices/413
