@uri=http://127.0.0.1:3005/api

###
# 1 returns all invoice items
GET {{uri}}/invoice_items

###
#2 query params - returns invoice_items sorted by InvoiceLineId desc
GET {{uri}}/invoice_items?sort=InvoiceLineId

###
# 3 returns all invoice_items and invoices
GET {{uri}}/invoice_items/invoices

###
# 3.5 returns all invoice_items and tracks 
# sorting ??
GET {{uri}}/invoice_items/tracks

###
#4 req.params -- returns specific id 
GET {{uri}}/invoice_items/256

###
#5 returns specific invoice id 
GET {{uri}}/invoice_items/25/invoices

###
#5.5 returns specific track by id 
GET {{uri}}/invoice_items/2/tracks

###
#6 Inserts row
#  TrackId was too high.
POST {{uri}}/invoice_items
Content-Type: application/json

{
   "InvoiceId": 412,
    "TrackId": 3177,
    "UnitPrice": 29.99,
    "Quantity": 4
  }

###
#7 Updates row w/ router.put by :Id (349)
PUT {{uri}}/invoice_items/2240
Content-Type: application/json

{
    "InvoiceId": 412,
    "TrackId": 5577,
    "UnitPrice": 29.99,
    "Quantity": 4
  }

###
#8 Deletes row specified by :id
DELETE {{uri}}/invoice_items/350