@uri=http://127.0.0.1:3005/api

###
# 1
GET {{uri}}/invoices

###
# 2 sorted invoices 
GET {{uri}}/invoices?sort=CustomerId

### 
#3 req.params -- returns invoices with invoice_items
GET {{uri}}/invoices/invoice_items

###
# req.params -- returns specific id 
GET {{uri}}/invoices/417

###
# Inserts row 
POST {{uri}}/invoices
Content-Type: application/json

{
    "CustomerId": "58",
    "InvoiceDate": "2012-2-2 00:00:00",
    "BillingAddress": "12,Comminsing",
    "BillingCity": "Delited",
    "BillingState": "FLawda",
    "BillingCountry": "Indiana",
    "BillingPostalCode": "1017",
    "Total": "17.99"
  }
###
# Updates row w/ router.put by  primaryKey :Id 
PUT {{uri}}/invoices/417
Content-Type: application/json

{
      "BillingState": "FLorida"
  }

###
# Deletes row specified by :id
DELETE {{uri}}/invoices/413
