@uri=http://127.0.0.1:3005/api

###
GET {{uri}}/media_types

###
# query params
GET {{uri}}/media_types?sort=MediaTypeId

###
# req.params -- returns specific id 
GET {{uri}}/media_types/1

###
#  
GET {{uri}}/media_types/3/trac

###
# Inserts row
POST {{uri}}/media_types
Content-Type: application/json

{
  "Name": "Moe"
}

###
# Updates row w/ router.put by :Id   
PUT {{uri}}/media_types/7
Content-Type: application/json

{
  "Name": "Ayo"

}

###
# Deletes row specified by :id 
DELETE {{uri}}/media_types/6