@uri=http://127.0.0.1:3005/api

###
GET {{uri}}/playlists
###
# query params
GET {{uri}}/playlists?sort=PlaylistId

###
# req.params -- returns specific id (259)
GET {{uri}}/playlists/20

###
# Inserts row
POST {{uri}}/playlists
Content-Type: application/json

{
  "Name": "muad_the_freestyler"
}

###
# Updates row w/ router.put by :Id (349)
# Needs PlaylistId to update ----
PUT {{uri}}/playlists/24
Content-Type: application/json

{
  "Name": "OD_FlyClean"
}

###
# Deletes row specified by :id 
DELETE {{uri}}/playlists/23
